### ISSUE TITLE
Testing of age-structure code

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/epicyst#7]
For help see the packages current test and also https://r-pkgs.org/tests.html

**Comment by Mad206** [comment]
Code (testing) coverage with new age-structured model now increased from 40 to 64.8% (local testing using covr::package_coverage() )

**Comment by Mad206** [comment]
Code (testing) coverage with new age-structured model now increased from 64.8% to 95.64% - local testing using covr::package_coverage()
